# https://docs.docker.com/compose/compose-file/
name: democracy-lottery
services:
    server:
        build:
            context: ../
            dockerfile: ./server/Dockerfile
        env_file: .env
        ports:
            - ${PORT}:${PORT}
        restart: ${COMPOSE_RESTART_POLICY}
        mem_limit: ${COMPOSE_HARD_MEMORY_LIMIT}
        mem_reservation: ${COMPOSE_SOFT_MEMORY_LIMIT}
