name: Server CD

on:
    workflow_run:
        workflows: ['Server CI']
        types: [completed]
        branches: [main]

concurrency:
    group: server-deploy
    cancel-in-progress: true

jobs:
    deploy:
        name: Deploy to Production
        if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest
        timeout-minutes: 2

        steps:
            - name: Execute deploy script
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd services_v2/Democracy-Lottery
                      git reset --hard --quiet
                      git clean -d --force --quiet
                      git pull --quiet
                      cd server
                      docker compose up --build --detach
                      docker image prune --force
